/**
 * Types for the diagnosis bank. The data itself lives in `diagnosis.ts`, generated by
 * `scripts/import-bank.ts` from the handover `content/bank.json`. Values (answer codes,
 * section ids, colours) keep the Indonesian codes used by bank.json and the database spec,
 * so exported research data needs no remapping.
 */

export const ANSWER_VALUES = ["ya", "kadang", "belum"] as const;
export type AnswerValue = (typeof ANSWER_VALUES)[number];

export const SKIP_ANSWER = "lewati" as const;
export type StoredAnswer = AnswerValue | typeof SKIP_ANSWER;

export const SECTION_COLORS = ["hijau", "kuning", "merah"] as const;
export type SectionColor = (typeof SECTION_COLORS)[number];

export const TASK_KINDS = ["siapkan", "harian", "mingguan"] as const;
export type TaskKind = (typeof TASK_KINDS)[number];

export interface Section<SectionId extends string = string> {
  id: SectionId;
  label: string;
  /** Icon key from bank.json ("order", "box", "cash", "sale", "chat"). */
  icon: string;
  description: string;
}

export interface Question<
  SectionId extends string = string,
  QuestionId extends string = string,
  ProblemId extends string = string,
> {
  id: QuestionId;
  sectionId: SectionId;
  text: string;
  redAnswer: AnswerValue;
  yellowAnswer: AnswerValue;
  problemId: ProblemId;
  /** Reversed question: the third option reads "Tidak" and "Ya" is the red answer. */
  reversed: boolean;
  /** When set, the question may be skipped; the text completes "Lewati, …". */
  skipWhen: string | null;
}

export interface Problem<
  SectionId extends string = string,
  ProblemId extends string = string,
  SopId extends string = string,
> {
  id: ProblemId;
  sectionId: SectionId;
  title: string;
  rootCause: string;
  impact: string;
  sopId: SopId;
}

interface TaskBase {
  id: string;
  text: string;
}

export interface SetupTask extends TaskBase {
  kind: "siapkan";
  minutes: number;
}

export interface RoutineTask extends TaskBase {
  kind: "harian" | "mingguan";
  target: number;
  unit: string;
  /** Only applies when the situation occurs (e.g. "Ada komplain?"). */
  onlyWhenPresent: boolean;
}

export type Task = SetupTask | RoutineTask;

export interface Sop<SectionId extends string = string, SopId extends string = string> {
  id: SopId;
  sectionId: SectionId;
  title: string;
  goal: string;
  tasks: Task[];
}

export interface DiagnosisRules<SectionId extends string = string> {
  maxSopPerPack: number;
  redPoints: number;
  yellowPoints: number;
  redThreshold: number;
  yellowThreshold: number;
  /** Tie-break order when sections score the same. */
  sectionOrder: SectionId[];
  followUpDays: number;
}

export interface DiagnosisBankShape<
  SectionId extends string = string,
  QuestionId extends string = string,
  ProblemId extends string = string,
  SopId extends string = string,
> {
  version: string;
  rules: DiagnosisRules<SectionId>;
  sections: Section<SectionId>[];
  questions: Question<SectionId, QuestionId, ProblemId>[];
  problems: Problem<SectionId, ProblemId, SopId>[];
  sops: Sop<SectionId, SopId>[];
}
